{
 "title": "Basic Example",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "CoinPair",
    "query": "select distinct symbol from binge.trade_candles_agg"
   }
  ]
 },
 "panels": [
  {
   "title": "${CoinPair}",
   "type": "candlestick",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\r\n  timestamp as t,\r\n  open::Decimal128(8) as open,\r\n  high::Decimal128(8) as high,\r\n  low::Decimal128(8) as low,\r\n  close::Decimal128(8) as close,\r\n  volumeA::Decimal128(8) as volume\r\nfrom binge.trade_candles\r\nwhere\r\n  $__timeFilter(timestamp)\r\n  and symbol = '${CoinPair}'\r\norder by timestamp"
    }
   ]
  },
  {
   "title": "Per Second Trades",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "with\r\n  toStartOfSecond(tradeTime) as t\r\nselect\r\n  formatDateTime(t, '%T') as Time,\r\n  sum(quantity)::Decimal128(8) as Volume,\r\n  avg(price) as `Average Price`,\r\n  count() as Trades\r\nfrom binge.raw_trades\r\nwhere\r\n  $__timeFilter(tradeTime)\r\n  and symbol = '${CoinPair}'\r\ngroup by t\r\norder by t desc\r\nlimit 30"
    }
   ]
  },
  {
   "title": "Trade Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "select\r\n  subString(toString(tradeTime), 11, 13) as Time,\r\n  quantity::Decimal128(8) as Volume,\r\n  price as `Price`\r\nfrom binge.raw_trades\r\nwhere\r\n  $__timeFilter(tradeTime)\r\n  and symbol = '${CoinPair}'\r\norder by tradeTime desc\r\nlimit 50"
    }
   ]
  }
 ]
}